# frozen_string_literal: true

require_relative "rb/version"

module Openharness
  module Rb
    class Error < StandardError; end
  end
end

require_relative "rb/errors"
require_relative "rb/models/content_block"
require_relative "rb/models/conversation_message"
require_relative "rb/models/tool_result"
require_relative "rb/models/stream_events"
require_relative "rb/models/query_context"
require_relative "rb/models/tool_execution_context"
require_relative "rb/engine/cost_tracker"
require_relative "rb/api/provider_spec"
require_relative "rb/api/provider_registry"
require_relative "rb/api/retry_handler"
require_relative "rb/api/llm_adapter"
require_relative "rb/tools/base_tool"
require_relative "rb/tools/tool_registry"
require_relative "rb/tools/builtin/read_file_tool"
require_relative "rb/tools/builtin/write_to_file_tool"
require_relative "rb/tools/builtin/edit_file_tool"
require_relative "rb/tools/builtin/grep_tool"
require_relative "rb/tools/builtin/glob_tool"
require_relative "rb/tools/builtin/bash_tool"
require_relative "rb/tools/builtin/skill_tool"
require_relative "rb/tools/builtin/agent_tool"
require_relative "rb/tools/builtin/web_search_tool"
require_relative "rb/tools/builtin/web_fetch_tool"
require_relative "rb/tools/builtin/lsp_tool"
require_relative "rb/tools/builtin/notebook_edit_tool"
require_relative "rb/tools/builtin/create_task_tool"
require_relative "rb/tools/builtin/list_tasks_tool"
require_relative "rb/tools/builtin/stop_task_tool"
require_relative "rb/tools/builtin/get_task_output_tool"
require_relative "rb/permissions/permission_mode"
require_relative "rb/permissions/permission_decision"
require_relative "rb/permissions/path_rule"
require_relative "rb/permissions/permission_checker"
require_relative "rb/hooks/hook_event"
require_relative "rb/hooks/hook_definition"
require_relative "rb/hooks/hook_registry"
require_relative "rb/hooks/hook_executor"
require_relative "rb/mcp/mcp_server_config"
require_relative "rb/mcp/mcp_client_manager"
require_relative "rb/mcp/mcp_tool_adapter"
require_relative "rb/mcp/read_mcp_resource_tool"
require_relative "rb/skills/skill_definition"
require_relative "rb/skills/skill_registry"
require_relative "rb/plugins/plugin_manifest"
require_relative "rb/plugins/loaded_plugin"
require_relative "rb/plugins/plugin_loader"
require_relative "rb/memory/memory_header"
require_relative "rb/memory/tokenizer"
require_relative "rb/memory/memory_system"
require_relative "rb/agents/agent_definition"
require_relative "rb/agents/team_registry"
require_relative "rb/session/session_storage"
require_relative "rb/session/background_task_manager"
require_relative "rb/config/settings"
require_relative "rb/engine/system_prompt_builder"
require_relative "rb/engine/query_engine"
require_relative "rb/cli/interactive_session"
require_relative "rb/cli/setup_wizard"
require_relative "rb/cli/main"
require_relative "rb/harness"
